### ISSUE TITLE
The generator does not ask for username and password

### ISSUE THREAD

**Issue by markbrummel** [tfenster/ALRunner#2]
When trying to use the generator on a URL that has a username/password the extension returns a 401.

**Comment by tfenster** [comment]
Yes, that's why I've added missing authorization to known issues and implementing authorization to future ideas :)

I might be able to implement it between Christmas and new year

**Comment by markbrummel** [comment]
Please don't work for me in that period. Enjoy the time off.

I've already fixed it in another way. The solution is a bit more generic and uses reflection on the json.

The next problem that you will run into is that json can have objects as members and then you would have to generate multiple tables and connect them with guids. This is what I've done now to read the addresses from the API.

**Comment by tfenster** [comment]
Yes, that's the other known issue :) Nested structures are currently ignored

**Comment by tfenster** [comment]
I've pushed a new version which allows you to work around the missing auth because it allows you to just select whatever JSON you want and generate objects from it. With that you can download your JSON file e.g. in a browser, paste it into VS code and run generation. Obviously you will also need to implement auth in the generated objects

**Comment by markbrummel** [comment]
Workaround is fine for now. Saves me a shitload of time creating the tables manually.

Honestly I only need the table. I changed the code from AJ to search for the table and fields using recref and fieldref with some help from Gunnar on reading the values.
